name: 🚀 Validate and deploy datapack
env:
  MC_VERSION: '1.19'
on:
  push:
  workflow_dispatch:
    inputs:
      forceUpload:
        type: boolean
        description: "Force uploading all files"
      removeExtraFilesOnServer:
        type: boolean
        description: "Remove extra files on server"
        default: true
jobs:
  check:
    name: Check commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          minecraft: ${{ env.MC_VERSION }}
  deploy:
    name: Deploy datapack
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v2
      - uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: servers.minemakers.net
          port: 5657
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          compress: true
          localDir: '.'
          remoteDir: './shulker-rush/datapacks/shulker-rush/'
          exclude: '.git*/**,.gitattributes,.editorconfig,README.md,LICENSE'
          removeExtraFilesOnServer: true
